/**
 * `@marketak/shared` - the one place a money value, a status literal, an error
 * code, an RPC response or an RPC command is defined.
 *
 * The mobile app and the outbox Worker both import from here, and nothing else
 * defines any of them. That is AGENTS.md rule 11: a second money formatter
 * produces `29.50` on one screen and `٢٩٫٥٠` on another, and the difference is
 * invisible until a customer complains.
 *
 * Import from the package root (`@marketak/shared`). A deep path bypasses this
 * public surface, and a lint rule forbids it.
 *
 *   import { formatMoney, ORDER_STATUS, type Order } from "@marketak/shared";
 */

export {
  PIASTRES_PER_UNIT,
  FALLBACK_CURRENCY,
  BPS_DENOMINATOR,
  PRIMARY_LANGUAGE,
  toPiastres,
  fromPiastres,
  addPiastres,
  sumPiastres,
  multiplyByCount,
  multiplyByRateBps,
  bpsToPercent,
  percentToBps,
  formatMoney,
  formatMoneyWithCurrency,
  formatCount,
  formatRate,
  formatRateBps,
  formatWhen,
  formatDate,
  formatRelativeInZone,
  multiplierFromBps,
} from "./money.js";
export type { Piastres, Language } from "./money.js";

export {
  ORDER_STATUS,
  SUB_ORDER_STATUS,
  ASSIGNMENT_STATUS,
  PAYMENT_STATUS,
  SETTLEMENT_STATUS,
  PAYMENT_METHOD,
  PAYMENT_CHANNEL,
  COLLECTION_METHOD,
  DELIVERY_TYPE,
  DELIVERY_GROUPING,
  ITEM_STATUS,
  ACTOR_ROLE,
  CANCELLATION_ACTOR,
  RIDER_STATUS,
  VEHICLE_TYPE,
  ASSIGNED_BY,
  USER_ROLE,
  APP_ROLE,
  PLATFORM,
  AUTH_PROVIDER,
  VERTICAL_TYPE,
  PRICING_MODE,
  ADDRESS_LABEL,
  VENDOR_AVAILABILITY,
  WALLET_OWNER_TYPE,
  WALLET_STATUS,
  LEDGER_ACCOUNT_TYPE,
  LEDGER_ENTRY_TYPE,
  PAYOUT_TYPE,
  PAYOUT_STATUS,
  PAYOUT_LINE_TYPE,
  PAYOUT_LINE_SOURCE,
  COMMISSION_TYPE,
  COMMISSION_SCOPE,
  COMMISSION_APPLIES_TO,
  VOUCHER_DISCOUNT_TYPE,
  STAFF_ROLE,
  QUOTE_REJECTION,
  STATUS_VOCABULARIES,
} from "./status.js";

export type {
  OrderStatus,
  SubOrderStatus,
  AssignmentStatus,
  PaymentStatus,
  SettlementStatus,
  PaymentMethod,
  PaymentChannel,
  CollectionMethod,
  DeliveryType,
  DeliveryGrouping,
  ItemStatus,
  ActorRole,
  CancellationActor,
  RiderStatus,
  VehicleType,
  AssignedBy,
  UserRole,
  AppRole,
  Platform,
  AuthProvider,
  VerticalType,
  PricingMode,
  AddressLabel,
  VendorAvailability,
  WalletOwnerType,
  WalletStatus,
  LedgerAccountType,
  LedgerEntryType,
  PayoutType,
  PayoutStatus,
  PayoutLineType,
  PayoutLineSource,
  CommissionType,
  CommissionScope,
  CommissionAppliesTo,
  VoucherDiscountType,
  StaffRole,
  QuoteRejectionCode,
  StatusVocabularyName,
} from "./status.js";

export {
  APP_ERROR_CODES,
  RETIRED_ERROR_CODES,
  BEHAVIOUR_CODES,
  ERROR_MESSAGE_PATTERN,
  AppError,
  isAppError,
  isAppErrorCode,
  kindOfErrorCode,
  parseServerMessage,
  parseAppError,
} from "./errors.js";
export type { AppErrorCode, AppErrorKind, ParsedError } from "./errors.js";

export type {
  SelectedOption,
  Uuid,
  ProfileStatus,
  Address,
  CartItem,
  UpsertCartItemResult,
  RemoveCartItemResult,
  QuoteTotals,
  QuoteFeeBreakdown,
  QuoteVendorSplit,
  QuoteLimits,
  QuoteRejection,
  QuoteResult,
  PlaceOrderResult,
  Order,
  OrderStatusHistoryEntry,
  OrderItem,
  CancelOrderResult,
  RiderProfile,
  AvailableOrder,
  ClaimOrderResult,
  BeginCollectionResult,
  CollectCashResult,
  CompleteDeliveryResult,
  VendorFeedItem,
  VendorFeed,
  CatalogSearchHit,
  DeviceToken,
} from "./dto.js";

export type {
  CompleteProfileArgs,
  UpdateProfilePatch,
  AddressPatch,
  UpsertAddressArgs,
  SetDefaultAddressArgs,
  DeleteAddressArgs,
  UpsertCartItemArgs,
  RemoveCartItemArgs,
  QuoteOrderArgs,
  PlaceOrderArgs,
  CancelOrderArgs,
  VendorFeedArgs,
  SearchCatalogArgs,
  AvailableOrdersArgs,
  ClaimOrderArgs,
  TransitionOrderArgs,
  BeginCollectionArgs,
  CollectCashArgs,
  CollectWalletArgs,
  CompleteDeliveryArgs,
  EffectiveCashLimitArgs,
  RegisterDeviceTokenArgs,
  DateWindowArgs,
} from "./commands.js";

export { renderTemplate, isSendable } from "./worker.js";
export type {
  TemplateRow,
  RenderedNotification,
  ClaimedNotification,
  MarkResult,
  SendOutcome,
  DeviceTokenRow,
} from "./worker.js";
