-- =============================================================================
-- 03_tables_vendors_and_catalog.sql
-- Merchants, their taxonomy, their trading calendar, and the menu.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- brands: optional parent brand shared by several vendor storefronts.
-- -----------------------------------------------------------------------------
create table public.brands
(
  id uuid not null default gen_random_uuid(),
  name text not null,
  name_ar text,
  logo_path text,
  is_active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  deleted_at timestamp with time zone,

  constraint brands_pkey primary key PRIMARY KEY (id)
);

-- -----------------------------------------------------------------------------
-- cuisines: global taxonomy. `*_normalized` columns are generated by
-- normalize_text_v1() (unaccent + lowercase + collapse) and are what the
-- trigram search indexes actually index.
-- -----------------------------------------------------------------------------
create table public.cuisines
(
  id uuid not null default gen_random_uuid(),
  code text not null,
  name text not null,
  name_ar text not null,
  sort_order integer not null default 0,
  name_normalized text default normalize_text_v1(name),
  name_ar_normalized text default normalize_text_v1(name_ar),
  deleted_at timestamp with time zone,
  updated_at timestamp with time zone not null default now(),

  constraint cuisines_code_key unique UNIQUE (code),
  constraint cuisines_pkey primary key PRIMARY KEY (id)
);

-- -----------------------------------------------------------------------------
-- vendors: the merchant. `is_open` is the operational switch; `auto_open`
-- lets the opening hours flip it automatically. `menu_version` is bumped by
-- trigger on any catalog write so clients can cheaply detect menu changes.
-- -----------------------------------------------------------------------------
create table public.vendors
(
  id uuid not null default gen_random_uuid(),
  slug text not null,
  name text not null,
  name_ar text not null,
  legal_name text,
  brand_id uuid,
  vertical_type text not null,
  city_id uuid not null,
  area_id uuid not null,
  latitude numeric(9,6) not null,
  longitude numeric(9,6) not null,
  geohash_prefix text not null,
  delivery_radius_km numeric(4,2) not null default 8,
  is_open boolean not null default false,
  is_busy boolean not null default false,
  auto_open boolean not null default true,
  is_approved boolean not null default false,
  is_active boolean not null default true,
  capacity_per_slot integer,
  reject_rate numeric(5,4) not null default 0,
  delivery_fee_override integer,
  minimum_order_value integer not null default 0,
  prep_time_minutes integer not null default 15,
  prep_time_max_minutes integer not null default 30,
  rating_avg numeric(3,2) not null default 0,
  rating_count integer not null default 0,
  menu_version integer not null default 1,
  logo_path text,
  description text,
  description_ar text,
  contact_phone text,
  contact_landline text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  deleted_at timestamp with time zone,
  name_normalized text default normalize_text_v1(name),
  name_ar_normalized text default normalize_text_v1(name_ar),
  description_normalized text default normalize_text_v1(description),

  constraint delivery_fee_override_valid check CHECK (((delivery_fee_override IS NULL) OR (delivery_fee_override >= 0))),
  constraint minimum_order_value_nonneg check CHECK ((minimum_order_value >= 0)),
  constraint prep_window_valid check CHECK (((prep_time_max_minutes IS NULL) OR (prep_time_minutes IS NULL) OR (prep_time_max_minutes >= prep_time_minutes))),
  constraint vendors_pkey primary key PRIMARY KEY (id),
  constraint vendors_rating_avg_check check CHECK (((rating_avg >= (0)::numeric) AND (rating_avg <= (5)::numeric))),
  constraint vendors_vertical_type_check check CHECK ((vertical_type = ANY (ARRAY['food'::text, 'grocery'::text, 'pharmacy'::text, 'flowers'::text, 'bakery'::text, 'others'::text])))
);

-- -----------------------------------------------------------------------------
-- vendor_cuisines / vendor_areas / vendor_staff: the many-to-many edges off a
-- vendor. All are soft-deletable, all cascade on vendor deletion.
-- -----------------------------------------------------------------------------
create table public.vendor_cuisines
(
  vendor_id uuid not null,
  cuisine_id uuid not null,
  deleted_at timestamp with time zone,
  updated_at timestamp with time zone not null default now(),

  constraint vendor_cuisines_pkey primary key PRIMARY KEY (vendor_id, cuisine_id)
);

-- vendor_areas: which areas a vendor delivers to, and the per-vendor ETA and
-- fee override for that area. Overrides win over the zone defaults.
create table public.vendor_areas
(
  vendor_id uuid not null,
  area_id uuid not null,
  delivery_fee_override integer,
  eta_minutes integer not null default 20,
  eta_maxutes integer not null default 40,
  is_active boolean not null default true,
  deleted_at timestamp with time zone,
  updated_at timestamp with time zone not null default now(),

  constraint vendor_areas_pkey primary key PRIMARY KEY (vendor_id, area_id)
);

-- vendor_staff: users who may act on behalf of a vendor, with the two
-- independent permissions the console needs.
create table public.vendor_staff
(
  id uuid not null default gen_random_uuid(),
  user_id uuid not null,
  vendor_id uuid not null,
  staff_role text not null default 'staff'::text,
  can_edit_menu boolean not null default false,
  can_manage_orders boolean not null default true,
  created_at timestamp with time zone not null default now(),
  deleted_at timestamp with time zone,
  updated_at timestamp with time zone not null default now(),

  constraint vendor_staff_pkey primary key PRIMARY KEY (id),
  constraint vendor_staff_staff_role_check check CHECK ((staff_role = ANY (ARRAY['owner'::text, 'manager'::text, 'staff'::text, 'cashier'::text]))),
  constraint vendor_staff_user_id_vendor_id_key unique UNIQUE (user_id, vendor_id)
);

-- -----------------------------------------------------------------------------
-- vendor_schedules: opening hours as (day_of_week, slot) rows. `slot` allows
-- two windows a day (lunch / dinner). `is_closed` keeps the row so history and
-- analytics survive a closure.
-- -----------------------------------------------------------------------------
create table public.vendor_schedules
(
  id uuid not null default gen_random_uuid(),
  vendor_id uuid not null,
  day_of_week smallint not null,
  slot smallint not null default 0,
  opens_at time without time zone not null,
  closes_at time without time zone not null,
  is_closed boolean not null default false,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  deleted_at timestamp with time zone,

  constraint vendor_schedules_check check CHECK ((closes_at > opens_at)),
  constraint vendor_schedules_day_of_week_check check CHECK (((day_of_week >= 0) AND (day_of_week <= 6))),
  constraint vendor_schedules_pkey primary key PRIMARY KEY (id),
  constraint vendor_schedules_vendor_id_day_of_week_slot_key unique UNIQUE (vendor_id, day_of_week, slot)
);

-- -----------------------------------------------------------------------------
-- vendor_holidays: closure dates. One row per (vendor, date).
-- -----------------------------------------------------------------------------
create table public.vendor_holidays
(
  id uuid not null default gen_random_uuid(),
  vendor_id uuid not null,
  holiday_date date not null,
  reason text,
  created_at timestamp with time zone not null default now(),
  deleted_at timestamp with time zone,
  updated_at timestamp with time zone not null default now(),

  constraint vendor_holidays_pkey primary key PRIMARY KEY (id),
  constraint vendor_holidays_vendor_id_holiday_date_key unique UNIQUE (vendor_id, holiday_date)
);

-- -----------------------------------------------------------------------------
-- menu_categories: vendor menu sections.
-- -----------------------------------------------------------------------------
create table public.menu_categories
(
  id uuid not null default gen_random_uuid(),
  vendor_id uuid not null,
  name text not null,
  name_ar text,
  description text,
  display_order integer not null default 0,
  is_available boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  deleted_at timestamp with time zone,
  name_normalized text default normalize_text_v1(name),
  name_ar_normalized text default normalize_text_v1(name_ar),

  constraint menu_categories_pkey primary key PRIMARY KEY (id)
);

-- -----------------------------------------------------------------------------
-- menu_items: sellable line. `pricing_mode` decides whether price comes from
-- base_price ('fixed') or from a chosen menu_item_sizes row ('sized').
-- `stock_count IS NULL` means unlimited. vendor_id is denormalised from
-- category_id by trigger so item search never needs the join.
-- -----------------------------------------------------------------------------
create table public.menu_items
(
  id uuid not null default gen_random_uuid(),
  category_id uuid not null,
  vendor_id uuid not null,
  name text not null,
  name_ar text,
  description text,
  description_ar text,
  pricing_mode text not null default 'fixed'::text,
  base_price integer,
  is_available boolean not null default true,
  stock_count integer,
  preparation_time_minutes integer,
  image_path text,
  display_order integer not null default 0,
  nutritional_info jsonb,
  allergens jsonb,
  ingredients jsonb,
  tags text[] not null default '{}'::text[],
  calories integer,
  is_spicy boolean not null default false,
  is_vegetarian boolean not null default false,
  is_featured boolean not null default false,
  is_new boolean not null default false,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  deleted_at timestamp with time zone,
  name_normalized text default normalize_text_v1(name),
  name_ar_normalized text default normalize_text_v1(name_ar),
  ingredients_normalized text default normalize_text_v1(ingredients),

  constraint fixed_item_has_price check CHECK (((pricing_mode <> 'fixed'::text) OR (base_price IS NOT NULL))),
  constraint menu_items_base_price_check check CHECK (((base_price IS NULL) OR (base_price >= 0))),
  constraint menu_items_pkey primary key PRIMARY KEY (id),
  constraint menu_items_pricing_mode_check check CHECK ((pricing_mode = ANY (ARRAY['fixed'::text, 'sized'::text]))),
  constraint menu_items_stock_count_check check CHECK (((stock_count IS NULL) OR (stock_count >= 0)))
);

-- -----------------------------------------------------------------------------
-- menu_item_sizes: the price variants of a 'sized' item. Exactly one row must
-- be `is_default` (enforced by trigger).
-- -----------------------------------------------------------------------------
create table public.menu_item_sizes
(
  id uuid not null default gen_random_uuid(),
  item_id uuid not null,
  name text not null,
  name_ar text,
  price integer not null,
  is_default boolean not null default false,
  is_available boolean not null default true,
  calories integer,
  display_order integer not null default 0,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  deleted_at timestamp with time zone,

  constraint menu_item_sizes_pkey primary key PRIMARY KEY (id),
  constraint menu_item_sizes_price_check check CHECK ((price >= 0))
);

-- -----------------------------------------------------------------------------
-- item_options: a customisation group on an item (e.g. "Size", "Spice level")
-- with min/max selection cardinality.
-- -----------------------------------------------------------------------------
create table public.item_options
(
  id uuid not null default gen_random_uuid(),
  item_id uuid not null,
  name text not null,
  name_ar text,
  is_required boolean not null default false,
  min_selections integer not null default 0,
  max_selections integer not null default 1,
  display_order integer not null default 0,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  deleted_at timestamp with time zone,
  is_available boolean not null default true,

  constraint item_options_pkey primary key PRIMARY KEY (id),
  constraint option_selections_sane check CHECK (((max_selections >= min_selections) AND ((max_selections > 0) OR (min_selections = 0))))
);

-- -----------------------------------------------------------------------------
-- option_choices: the selectable values in an option group. `price_modifier` is
-- added to the item price at quote time; it may be negative.
-- -----------------------------------------------------------------------------
create table public.option_choices
(
  id uuid not null default gen_random_uuid(),
  option_id uuid not null,
  name text not null,
  name_ar text,
  price_modifier integer not null default 0,
  is_default boolean not null default false,
  is_available boolean not null default true,
  stock_count integer,
  calories integer,
  display_order integer not null default 0,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  deleted_at timestamp with time zone,

  constraint option_choices_pkey primary key PRIMARY KEY (id),
  constraint price_modifier_floor check CHECK ((price_modifier >= '-100000'::integer))
);